---

  - hosts: ocnos
    gather_facts: no

    tasks:
      - name: Create configuration templates for AGG node
        template:
          src: "templates/{{ ansible_network_os }}_interface.j2"
          dest: "configs/{{ inventory_hostname }}interface.config"
      - name: load configs interface
        ocnos_config:
          src: "configs/{{ inventory_hostname }}interface.config"
      - name: show interface config ocnos
        cli_command:
          command: show run 
        register: result1
      - name: debug
        debug:
          msg: "{{ result1.stdout_lines }}"
      - name: show interface brief
        cli_command:
          command: show int brief
        register: result2
      - name: debug
        debug:
          msg: "{{ result2.stdout_lines }}"
