---
  - hosts: ocnos
    gather_facts: no
    

    tasks:
    
      - name: configure rsvp
        template:
          src: "templates/{{ ansible_network_os }}_rsvp.j2"
          dest: "configs/{{inventory_hostname}}.config"
     
      - name: load RSVP config ocnos
        ocnos_config:
          src: "configs/{{ inventory_hostname }}.config"

      
      - pause: seconds=15

      - name: show RSVP config ocnos    
        cli_command:
          command: show  rsvp  session            
        register: result
        
      - name: debug
        debug:
          msg: "{{ result.stdout_lines }}"
          