---
  - hosts: ocnos
    gather_facts: no
    

    tasks:
          
      - name: configure static routes
        template:
          src: "templates/{{ ansible_network_os }}_static_routes.j2"
          dest: "configs/{{inventory_hostname}}.config"
     
      - name: load static routes config ocnos
        ocnos_config:
          src: "configs/{{ inventory_hostname }}.config"

      
      - name: show static routes config ocnos    
        cli_command:
          command: show ip static-route              
        register: result
        
      - name: debug
        debug:
          msg: "{{ result.stdout_lines }}"
